# Generated by Django 6.0.1 on 2026-01-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('create_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_add', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
